server:
  port: 11000
spring:
  application:
    name: 08springboot-cloud-zuul-reg
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"