server:
  port: 12000
spring:
  application:
    name: 09spring-cloud-zuul-filter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"