server:
  port: 13000
spring:
  application:
    name: 10spring-cloud-zuul-api
  redis:
    host: 192.168.188.129
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"