server:
  port: 7000
spring:
  application:
    name: 05spring-cloud-feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
feign:
  hystrix:
    enabled: true